# Generated by Django 4.0.2 on 2022-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_remove_students_id_students_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student_id',
        ),
        migrations.AddField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
